# This file was generated by RNOH autolinking.
# DO NOT modify it manually, your changes WILL be overwritten.
cmake_minimum_required(VERSION 3.5)

# @actor RNOH_APP
function(autolink_libraries target)
    add_subdirectory("${OH_MODULES_DIR}/@react-native-ohos/react-native-image-picker/src/main/cpp" ./rnoh_image_picker)
    add_subdirectory("${OH_MODULES_DIR}/@react-native-ohos/react-native-sqlite-storage/src/main/cpp" ./rnoh_sqlite_storage)
    add_subdirectory("${OH_MODULES_DIR}/@react-native-ohos/react-native-fs/src/main/cpp" ./rnoh_fs)

    set(AUTOLINKED_LIBRARIES
        rnoh_image_picker
        rnoh_sqlite_storage
        rnoh_fs
    )

    foreach(lib ${AUTOLINKED_LIBRARIES})
        target_link_libraries(${target} PUBLIC ${lib})
    endforeach()
endfunction()
