/*
 * This file was generated by RNOH autolinking.
 * DO NOT modify it manually, your changes WILL be overwritten.
 */
// clang-format off
#pragma once
#include "RNOH/Package.h"
#include "RNImagePickerPackage.h"
#include "SqliteStoragePackage.h"
#include "RNFSPackage.h"

std::vector<rnoh::Package::Shared> createRNOHPackages(const rnoh::Package::Context &ctx) {
  return {
    std::make_shared<rnoh::RNImagePickerPackage>(ctx),
    std::make_shared<rnoh::SqliteStoragePackage>(ctx),
    std::make_shared<rnoh::RNFSPackage>(ctx),
  };
}
